# Distributed under the MIT License.
# See LICENSE.txt for details.

name: Parse compiler

description: |
  Parse the compiler name and version from the input and set the environment
  variables CC, CXX, FC, COMPILER_ID, and COMPILER_VERSION.

inputs:
  compiler:
    description: Compiler to parse, e.g. 'gcc-10'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        if [[ ${{ inputs.compiler }} =~ (gcc|clang|nvcc)-([0-9\.\-]+) ]]; then
          COMPILER_ID=${BASH_REMATCH[1]}
          COMPILER_VERSION=${BASH_REMATCH[2]}
          if [[ $COMPILER_ID = gcc ]]; then
            CC=gcc-${COMPILER_VERSION};
            CXX=g++-${COMPILER_VERSION};
            FC=gfortran-${COMPILER_VERSION};
          elif [[ $COMPILER_ID = clang ]]; then
            CC=clang-${COMPILER_VERSION};
            CXX=clang++-${COMPILER_VERSION};
            FC=gfortran-11;
          elif [[ $COMPILER_ID = nvcc ]]; then
            CC=gcc;
            CXX=nvcc;
            FC=gfortran-11;
          fi
        fi
        echo "CC=$CC" >> $GITHUB_ENV
        echo "CXX=$CXX" >> $GITHUB_ENV
        echo "FC=$FC" >> $GITHUB_ENV
        echo "COMPILER_ID=$COMPILER_ID" >> $GITHUB_ENV
        echo "COMPILER_VERSION=$COMPILER_VERSION" >> $GITHUB_ENV
      shell: bash
